// Generated by gencpp from file vision/pub_correction.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_PUB_CORRECTION_H
#define VISION_MESSAGE_PUB_CORRECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct pub_correction_
{
  typedef pub_correction_<ContainerAllocator> Type;

  pub_correction_()
    : visionCorrectionPosX(0)
    , visionCorrectionPosY(0)
    , visionCorrectionPosT(0)  {
    }
  pub_correction_(const ContainerAllocator& _alloc)
    : visionCorrectionPosX(0)
    , visionCorrectionPosY(0)
    , visionCorrectionPosT(0)  {
  (void)_alloc;
    }



   typedef int16_t _visionCorrectionPosX_type;
  _visionCorrectionPosX_type visionCorrectionPosX;

   typedef int16_t _visionCorrectionPosY_type;
  _visionCorrectionPosY_type visionCorrectionPosY;

   typedef int16_t _visionCorrectionPosT_type;
  _visionCorrectionPosT_type visionCorrectionPosT;





  typedef boost::shared_ptr< ::vision::pub_correction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::pub_correction_<ContainerAllocator> const> ConstPtr;

}; // struct pub_correction_

typedef ::vision::pub_correction_<std::allocator<void> > pub_correction;

typedef boost::shared_ptr< ::vision::pub_correction > pub_correctionPtr;
typedef boost::shared_ptr< ::vision::pub_correction const> pub_correctionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::pub_correction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::pub_correction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::pub_correction_<ContainerAllocator1> & lhs, const ::vision::pub_correction_<ContainerAllocator2> & rhs)
{
  return lhs.visionCorrectionPosX == rhs.visionCorrectionPosX &&
    lhs.visionCorrectionPosY == rhs.visionCorrectionPosY &&
    lhs.visionCorrectionPosT == rhs.visionCorrectionPosT;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::pub_correction_<ContainerAllocator1> & lhs, const ::vision::pub_correction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision::pub_correction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::pub_correction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::pub_correction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::pub_correction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::pub_correction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::pub_correction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::pub_correction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0454f97ba8e72f3736158200b3f92c4";
  }

  static const char* value(const ::vision::pub_correction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0454f97ba8e72f3ULL;
  static const uint64_t static_value2 = 0x736158200b3f92c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::pub_correction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/pub_correction";
  }

  static const char* value(const ::vision::pub_correction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::pub_correction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 visionCorrectionPosX\n"
"int16 visionCorrectionPosY\n"
"int16 visionCorrectionPosT\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::vision::pub_correction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::pub_correction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.visionCorrectionPosX);
      stream.next(m.visionCorrectionPosY);
      stream.next(m.visionCorrectionPosT);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pub_correction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::pub_correction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::pub_correction_<ContainerAllocator>& v)
  {
    s << indent << "visionCorrectionPosX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.visionCorrectionPosX);
    s << indent << "visionCorrectionPosY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.visionCorrectionPosY);
    s << indent << "visionCorrectionPosT: ";
    Printer<int16_t>::stream(s, indent + "  ", v.visionCorrectionPosT);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_PUB_CORRECTION_H
