(cl:in-package vision-msg)
(cl:export '(VISIONCORRECTIONPOSX-VAL
          VISIONCORRECTIONPOSX
          VISIONCORRECTIONPOSY-VAL
          VISIONCORRECTIONPOSY
          VISIONCORRECTIONPOST-VAL
          VISIONCORRECTIONPOST
))