(cl:in-package vision-msg)
(cl:export '(VISIONFRONTPOSX-VAL
          VISIONFRONTPOSX
          VISIONFRONTPOSY-VAL
          VISIONFRONTPOSY
          VISIONFRONTPOST-VAL
          VISIONFRONTPOST
          VISIONFRONTDETECTBALL-VAL
          VISIONFRONTDETECTBALL
))