(cl:in-package vision-msg)
(cl:export '(VISIONOMNIPOSX-VAL
          VISIONOMNIPOSX
          VISIONOMNIPOSY-VAL
          VISIONOMNIPOSY
          VISIONOMNIPOST-VAL
          VISIONOMNIPOST
          VISIONOMNIDREAL-VAL
          VISIONOMNIDREAL
          VISIONOMNIDETECTBALL-VAL
          VISIONOMNIDETECTBALL
          VISIONOMNIPREDICX-VAL
          VISIONOMNIPREDICX
          VISIONOMNIPREDICY-VAL
          VISIONOMNIPREDICY
          VISIONOMNIPREDICT-VAL
          VISIONOMNIPREDICT
          VISIONOMNISPEEDX-VAL
          VISIONOMNISPEEDX
          VISIONOMNISPEEDY-VAL
          VISIONOMNISPEEDY
          VISIONOMNIPASSING-VAL
          VISIONOMNIPASSING
))